const path = require('path');
const express = require('express');
const http = require('http');
const socketIO = require('socket.io');

const {generateMessage, generateLocationMessage} = require('./utils/message');
const {Users} = require ('./utils/users');
const{isRealString} = require('./utils/validation');

const publicPath = path.join(__dirname, '../public');
//console.log(publicPath);

const port = process.env.PORT || 2000;
var app = express();
var server = http.createServer(app);
var io = socketIO(server);
var users = new Users();

app.use(express.static(publicPath));

//register an event e.g: connection
io.on('connection', (socket) => {
  console.log('Server saying: New user connected now');

  //*** socket.emit connect to single connection ***
  //socket.emit from Admin text Welcome to the chat app
    // socket.emit('createMessage_server', {
    //   from: 'Admin',
    //   text: 'Welcome to our Chat!'
    // });

//socket.emit('createMessage_server', generateMessage('Admin', 'Welcome to our Chat App!'));

  // socket.broadcast.emit Admin text new user Joined
    //  socket.broadcast.emit('createMessage_server', {
    //    from: 'Admin',
    //    text: 'New User Join'
    //  });
//socket.broadcast.emit('createMessage_server', generateMessage('Admin','New User Join'));


  //*** socket.emit connect to single connection ***
  // sending email server to client, emit need to be under io.on
  // emit similar to listen. creating an object because allow to send many things as wish
        // socket.emit('createMessage_server', {
        //   from: 'mike@example.com',
        //   text: 'From server to Hallo Aziz....',
        //   createAt: 123
        // });

   // passing params object and call for acknowledgement
   // 1st validate data e.g not empty string or number ..
   socket.on('join', (params, callback) => {
     if (!isRealString(params.name) || !isRealString(params.room)) {
       return callback('Name & room name are required!');
     }

     socket.join(params.room);
     users.removeUser(socket.id);
     users.addUser(socket.id, params.name, params.room);

     // passing to the room name and updating user list
     io.to(params.room).emit('updateUserList', users.getUserList(params.room));
     // socket.leave('The Office Fans');

    // io.emit -> io.to('The Office Fans').emit
    // socket.broadcast.emit -> socket.broadcast.to('The Office Fans').emit
    // socket.emit

     socket.emit('createMessage_server', generateMessage('Admin', 'Welcome to our Chat App!'));
     socket.broadcast.to(params.room).emit('createMessage_server', generateMessage('Admin', `${params.name} has joined.`));
     callback();
   });


  //*** io.emit -> emits to every single connection ***
  // server receving email from client
  socket.on('createMessage_client', (msgRecvServer, callback) =>{
    console.log('Msg Recv Server:', msgRecvServer);
    //io.emit-> server forwarding the receving msg to all clients/connection
        // io.emit('createMessage_server', {
        //   from: msgRecvServer.from,
        //   text: msgRecvServer.text,
        //   //generated by server to prevent a specific client from spoofy when a msg was created
        //   createAt: new Date().getTime()
        // });

        var user = users.getUser(socket.id);

        if (user && isRealString(msgRecvServer.text)) {
            io.to(user.room).emit('createMessage_server', generateMessage(user.name, msgRecvServer.text));
        }

        callback("Server said done!"); // trigered callback to client with given some date
      //  callback("");

    // broadcast allows to send msg to all except the msg sender
      // socket.broadcast.emit('createMessage_server', {
      //   from: msgRecvServer.from,
      //   text: msgRecvServer.text,
      //   createAt: new Date().getTime()
      // });
});
      socket.on('creategeoLocationClient', (coords) => {
        // io.emit('createMessage_server', generateMessage('Admin',
        //             `${coords.latitude}, ${coords.longitude}`) );

        var user = users.getUser(socket.id);

        if (user) {
              io.to(user.room).emit('newLocation_server', generateLocationMessage(user.name, coords.latitude, coords.longitude));
        }

      });



  // if user disconnect then server respond here
  socket.on('disconnect', () => {
    //console.log('Server saying: user disconnected now');
    var user = users.removeUser(socket.id);

    if (user) {
      io.to(user.room).emit('updateUserList', users.getUserList(user.room));
      io.to(user.room).emit('createMessage_server', generateMessage('Admin', `${user.name} has left.`) );
    }
  });

});

//app.listen(port, function(){
server.listen(port, function(){
  console.log(`Server listening on port ${port}`);
});
